# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadhar',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='wallet',
            field=models.CharField(max_length=200),
        ),
    ]
